version: 2.1

build: &build
  docker:
    - image: cimg/base:2020.09
  working_directory: /tmp/src/qsirecon_build
  steps:
    - checkout
    - setup_remote_docker:
        version: docker24
    - run:
        name: Check whether build should be skipped
        command: |
          if [[ -n "$CIRCLE_TAG" ]]; then
            source setup_build.sh
            required_tag=$(printenv ${VERSION_TAG})
            needs_build=1
            # Do we need to build this?
            dpkg --compare-versions "${required_tag}" lt "${CIRCLE_TAG}" \
                && needs_build=0

            echo "needs_build=${needs_build}"
            echo "required_tag=${required_tag}"
            echo "CIRCLE_TAG=${CIRCLE_TAG}"

            if [[ ${needs_build} -eq 0 ]]; then
              echo "Older version of dependency already exists, no need to build"
              circleci-agent step halt
            fi
          else
            echo "skipping non-tagged versions"
            circleci-agent step halt
          fi

    - run:
        name: Build and push
        no_output_timeout: 2h
        command: |
          source setup_build.sh
          DOCKER_BUILDKIT=1 \
          BUILDKIT_PROGRESS=plain \
          docker build \
            --rm=false \
            -f ${BUILD_FILE} \
            --build-arg TAG_ANTS=${TAG_ANTS} \
            -t pennlinc/${IMG_NAME}:${CIRCLE_TAG} .

          if [[ -n "$DOCKER_PASS" ]]; then
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push pennlinc/${IMG_NAME}:$CIRCLE_TAG
          fi

jobs:

  build:
    environment:
      TZ: "/usr/share/zoneinfo/America/New_York"
    docker:
      - image: cimg/base:2020.09
    working_directory: /tmp/src/qsirecon_build
    steps:
      - checkout
      - setup_remote_docker:
         version: docker24

      - run:
          name: Build and push
          no_output_timeout: 5h
          command: |
            if [[ -n "$CIRCLE_TAG" ]]; then
              source setup_build.sh
              do_build
              docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
              docker push pennlinc/qsirecon_build:$CIRCLE_TAG
            fi

  deployable:
    docker:
      - image: busybox:latest
    steps:
      - run: echo Deploying!

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
